name = "golang"
version = "1.0"

[web]
listen = ":9527"
debugLevel = "debug"

[db]
dbName = "postgres"
user = "ows"
password = "thingple"
host = "10.211.55.5"
port = 5439
database = "postgres"
ssl = "disable" #require/verify-full/verify-ca/disable


[redis]
password = "123456"
addrs = "10.211.55.5:6379"
poolSize = 1
db = 0