package gencode

// DDD 代码生成模板(表驱动,与 gbx gen 风格同构)。

const tmplModel = `// Code generated by go-blackbox gencode; DO NOT EDIT manually (re-generate to update).
package model

import (
	"time"

	"github.com/Connorig/go-blackbox/framework/database/model"
)

// {{.ModelName}} 由 gencode 从表 {{.Table.Name}} 生成。
type {{.ModelName}} struct {
	model.StandardModel // 基础字段:id / gmt_create / gmt_modified / is_deleted
{{- range .GoFields}}
	{{.Name}} {{.GoType}} ` + "`gorm:\"column:{{.Column}}\"`" + ` // {{.Comment}}
{{- end}}
}

// TableName 表名。
func ({{.ModelName}}) TableName() string {
	return "{{.Table.Name}}"
}
`

const tmplFilter = `// Code generated by go-blackbox gencode; DO NOT EDIT manually (re-generate to update).
package filter

// {{.ModelName}}Filter {{.Table.Name}} 查询过滤条件。
type {{.ModelName}}Filter struct {
	// Keyword 通用关键字(可选;按需在 repository 扩展匹配字段)。
	Keyword string
{{- range .GoFields}}
{{- if or (eq .GoType "string") (eq .GoType "int") (eq .GoType "int64")}}
	// {{.Name}} 精确匹配;零值不生效。
	{{.Name}} {{.GoType}}
{{- end}}
{{- end}}
	// Page/PageSize 分页(Page 从 1 开始;PageSize 默认 20,上限 100)。
	Page     int
	PageSize int
}

// Offset 分页偏移。
func (f *{{.ModelName}}Filter) Offset() int {
	if f.Page <= 1 {
		return 0
	}
	return (f.Page - 1) * f.Limit()
}

// Limit 分页大小。
func (f *{{.ModelName}}Filter) Limit() int {
	if f.PageSize <= 0 {
		return 20
	}
	if f.PageSize > 100 {
		return 100
	}
	return f.PageSize
}
`

const tmplRepository = `// Code generated by go-blackbox gencode; DO NOT EDIT manually (re-generate to update).
package repository

import (
	"context"

	apperr "github.com/Connorig/go-blackbox/component/error"
	"github.com/Connorig/go-blackbox/framework/database"
	"gorm.io/gorm"

	"{{.ModulePath}}/internal/filter"
	"{{.ModulePath}}/internal/model"
)

// {{.ModelName}}Repository {{.Table.Name}} 数据访问接口。
type {{.ModelName}}Repository interface {
	Create(ctx context.Context, record *model.{{.ModelName}}) error
	Update(ctx context.Context, record *model.{{.ModelName}}) error
	Delete(ctx context.Context, id int64) error
	GetByID(ctx context.Context, id int64) (*model.{{.ModelName}}, error)
	List(ctx context.Context, f filter.{{.ModelName}}Filter) ([]model.{{.ModelName}}, int64, error)
}

// {{.VarName}}Repository 实现。
type {{.VarName}}Repository struct{}

// New{{.ModelName}}Repository 创建仓储。
func New{{.ModelName}}Repository() {{.ModelName}}Repository {
	return &{{.VarName}}Repository{}
}

// db 获取数据库实例。
func (r *{{.VarName}}Repository) db(ctx context.Context) (*gorm.DB, error) {
	instance, err := datasource.Get()
	if err != nil {
		return nil, err
	}
	return instance.DB().WithContext(ctx), nil
}

// Create 创建(事务内执行)。
func (r *{{.VarName}}Repository) Create(ctx context.Context, record *model.{{.ModelName}}) error {
	return datasource.WithTx(ctx, func(tx *gorm.DB) error {
		return tx.Create(record).Error
	})
}

// Update 更新(事务内执行)。
func (r *{{.VarName}}Repository) Update(ctx context.Context, record *model.{{.ModelName}}) error {
	return datasource.WithTx(ctx, func(tx *gorm.DB) error {
		return tx.Updates(record).Error
	})
}

// Delete 逻辑删除。
func (r *{{.VarName}}Repository) Delete(ctx context.Context, id int64) error {
	db, err := r.db(ctx)
	if err != nil {
		return err
	}
	result := db.Delete(&model.{{.ModelName}}{}, id)
	if result.Error != nil {
		return result.Error
	}
	if result.RowsAffected == 0 {
		return apperr.New(apperr.CodeRequestParamError, "record not found")
	}
	return nil
}

// GetByID 详情。
func (r *{{.VarName}}Repository) GetByID(ctx context.Context, id int64) (*model.{{.ModelName}}, error) {
	db, err := r.db(ctx)
	if err != nil {
		return nil, err
	}
	var record model.{{.ModelName}}
	if err := db.First(&record, id).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, nil
		}
		return nil, err
	}
	return &record, nil
}

// List 分页 + 条件查询。
func (r *{{.VarName}}Repository) List(ctx context.Context, f filter.{{.ModelName}}Filter) ([]model.{{.ModelName}}, int64, error) {
	db, err := r.db(ctx)
	if err != nil {
		return nil, 0, err
	}
	query := db.Model(&model.{{.ModelName}}{})
	if f.Keyword != "" {
		query = query.Where("name LIKE ?", "%"+f.Keyword+"%")
	}
{{- range .GoFields}}
{{- if or (eq .GoType "string") (eq .GoType "int") (eq .GoType "int64")}}
	if f.{{.Name}} != "" || f.{{.Name}} != 0 {
		query = query.Where("{{.Column}} = ?", f.{{.Name}})
	}
{{- end}}
{{- end}}
	var total int64
	if err := query.Count(&total).Error; err != nil {
		return nil, 0, err
	}
	var records []model.{{.ModelName}}
	if err := query.Order("id DESC").Limit(f.Limit()).Offset(f.Offset()).Find(&records).Error; err != nil {
		return nil, 0, err
	}
	return records, total, nil
}
`

const tmplService = `// Code generated by go-blackbox gencode; DO NOT EDIT manually (re-generate to update).
package service

import (
	"context"
	"errors"

	"{{.ModulePath}}/internal/filter"
	"{{.ModulePath}}/internal/model"
	"{{.ModulePath}}/internal/repository"
)

var (
	err{{.ModelName}}NameRequired = errors.New("name is required")
	err{{.ModelName}}NotFound     = errors.New("record not found")
)

// {{.ModelName}}Service 业务接口。
type {{.ModelName}}Service interface {
	Create(ctx context.Context, record *model.{{.ModelName}}) (*model.{{.ModelName}}, error)
	Update(ctx context.Context, record *model.{{.ModelName}}) error
	Delete(ctx context.Context, id int64) error
	Get(ctx context.Context, id int64) (*model.{{.ModelName}}, error)
	List(ctx context.Context, f filter.{{.ModelName}}Filter) ([]model.{{.ModelName}}, int64, error)
}

// {{.VarName}}Service 实现。
type {{.VarName}}Service struct {
	repo repository.{{.ModelName}}Repository
}

// New{{.ModelName}}Service 创建业务服务。
func New{{.ModelName}}Service(repo repository.{{.ModelName}}Repository) {{.ModelName}}Service {
	return &{{.VarName}}Service{repo: repo}
}

// Create 创建。
func (s *{{.VarName}}Service) Create(ctx context.Context, record *model.{{.ModelName}}) (*model.{{.ModelName}}, error) {
	// 业务校验(按需扩展)
	if err := s.repo.Create(ctx, record); err != nil {
		return nil, err
	}
	return record, nil
}

// Update 更新。
func (s *{{.VarName}}Service) Update(ctx context.Context, record *model.{{.ModelName}}) error {
	if record.ID == 0 {
		return errors.New("id is required")
	}
	exist, err := s.repo.GetByID(ctx, record.ID)
	if err != nil {
		return err
	}
	if exist == nil {
		return err{{.ModelName}}NotFound
	}
	return s.repo.Update(ctx, record)
}

// Delete 删除。
func (s *{{.VarName}}Service) Delete(ctx context.Context, id int64) error {
	return s.repo.Delete(ctx, id)
}

// Get 详情。
func (s *{{.VarName}}Service) Get(ctx context.Context, id int64) (*model.{{.ModelName}}, error) {
	return s.repo.GetByID(ctx, id)
}

// List 列表。
func (s *{{.VarName}}Service) List(ctx context.Context, f filter.{{.ModelName}}Filter) ([]model.{{.ModelName}}, int64, error) {
	return s.repo.List(ctx, f)
}
`

const tmplHandler = `// Code generated by go-blackbox gencode; DO NOT EDIT manually (re-generate to update).
package handler

import (
	apperr "github.com/Connorig/go-blackbox/component/error"
	"github.com/Connorig/go-blackbox/framework/web"
	"github.com/kataras/iris/v12"

	"{{.ModulePath}}/internal/filter"
	"{{.ModulePath}}/internal/model"
	"{{.ModulePath}}/internal/service"
)

// {{.ModelName}}ListRequest 列表查询参数。
type {{.ModelName}}ListRequest struct {
	Keyword  string ` + "`url:\"keyword\"`" + `
	Page     int    ` + "`url:\"page\"`" + `
	PageSize int    ` + "`url:\"page_size\"`" + `
}

// List{{.ModelName}} GET {{.RoutePath}} 分页列表。
func List{{.ModelName}}(svc service.{{.ModelName}}Service) iris.Handler {
	return func(ctx iris.Context) {
		var request {{.ModelName}}ListRequest
		if err := ctx.ReadQuery(&request); err != nil {
			webiris.Fail(ctx, 400, apperr.CodeRequestParamError, "invalid query params")
			return
		}
		f := filter.{{.ModelName}}Filter{
			Keyword:  request.Keyword,
			Page:     request.Page,
			PageSize: request.PageSize,
		}
		list, total, err := svc.List(ctx.Request().Context(), f)
		if err != nil {
			webiris.RespondError(ctx, err)
			return
		}
		webiris.OK(ctx, map[string]interface{}{
			"list":      list,
			"total":     total,
			"page":      f.Page,
			"page_size": f.Limit(),
		})
	}
}

// Get{{.ModelName}} GET {{.RoutePath}}/{id} 详情。
func Get{{.ModelName}}(svc service.{{.ModelName}}Service) iris.Handler {
	return func(ctx iris.Context) {
		id := ctx.Params().GetInt64Default("id", 0)
		if id <= 0 {
			webiris.Fail(ctx, 400, apperr.CodeRequestParamError, "invalid id")
			return
		}
		record, err := svc.Get(ctx.Request().Context(), id)
		if err != nil {
			webiris.RespondError(ctx, err)
			return
		}
		if record == nil {
			webiris.Fail(ctx, 404, apperr.CodeRequestParamError, "record not found")
			return
		}
		webiris.OK(ctx, record)
	}
}

// Create{{.ModelName}} POST {{.RoutePath}} 创建。
func Create{{.ModelName}}(svc service.{{.ModelName}}Service) iris.Handler {
	return func(ctx iris.Context) {
		var record model.{{.ModelName}}
		if err := ctx.ReadJSON(&record); err != nil {
			webiris.Fail(ctx, 400, apperr.CodeJSONParseFailed, "invalid json body")
			return
		}
		created, err := svc.Create(ctx.Request().Context(), &record)
		if err != nil {
			webiris.RespondError(ctx, err)
			return
		}
		webiris.OK(ctx, created)
	}
}

// Update{{.ModelName}} PUT {{.RoutePath}}/{id} 更新。
func Update{{.ModelName}}(svc service.{{.ModelName}}Service) iris.Handler {
	return func(ctx iris.Context) {
		id := ctx.Params().GetInt64Default("id", 0)
		if id <= 0 {
			webiris.Fail(ctx, 400, apperr.CodeRequestParamError, "invalid id")
			return
		}
		var record model.{{.ModelName}}
		if err := ctx.ReadJSON(&record); err != nil {
			webiris.Fail(ctx, 400, apperr.CodeJSONParseFailed, "invalid json body")
			return
		}
		record.ID = id
		if err := svc.Update(ctx.Request().Context(), &record); err != nil {
			webiris.RespondError(ctx, err)
			return
		}
		webiris.OK(ctx, map[string]interface{}{"id": id, "updated": true})
	}
}

// Delete{{.ModelName}} DELETE {{.RoutePath}}/{id} 删除。
func Delete{{.ModelName}}(svc service.{{.ModelName}}Service) iris.Handler {
	return func(ctx iris.Context) {
		id := ctx.Params().GetInt64Default("id", 0)
		if id <= 0 {
			webiris.Fail(ctx, 400, apperr.CodeRequestParamError, "invalid id")
			return
		}
		if err := svc.Delete(ctx.Request().Context(), id); err != nil {
			webiris.RespondError(ctx, err)
			return
		}
		webiris.OK(ctx, map[string]interface{}{"id": id, "deleted": true})
	}
}
`

const tmplRoute = `// 路由注册(复制到 main.go 的 EnableWeb 回调中):
// repo := repository.New{{.ModelName}}Repository()
// svc := service.New{{.ModelName}}Service(repo)
// app.Get("{{.RoutePath}}", handler.List{{.ModelName}}(svc))
// app.Get("{{.RoutePath}}/{id:int64}", handler.Get{{.ModelName}}(svc))
// app.Post("{{.RoutePath}}", handler.Create{{.ModelName}}(svc))
// app.Put("{{.RoutePath}}/{id:int64}", handler.Update{{.ModelName}}(svc))
// app.Delete("{{.RoutePath}}/{id:int64}", handler.Delete{{.ModelName}}(svc))
`
